// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using infinitoBack.Data;

#nullable disable

namespace infinitoBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004135549_AjustarRelacionesReservas")]
    partial class AjustarRelacionesReservas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("infinitoBack.Models.Asiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Columna")
                        .HasColumnType("int");

                    b.Property<int>("Fila")
                        .HasColumnType("int");

                    b.Property<string>("NumeroAsiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PisoAsiento")
                        .HasColumnType("int");

                    b.Property<int>("PlantillaVehiculoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAsiento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantillaVehiculoId", "PisoAsiento", "Fila", "Columna")
                        .IsUnique();

                    b.ToTable("Asientos");
                });

            modelBuilder.Entity("infinitoBack.Models.AsignacionAsiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsientoId")
                        .HasColumnType("int");

                    b.Property<int>("ExcursionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReservaClienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsientoId");

                    b.HasIndex("ReservaClienteId")
                        .IsUnique();

                    b.HasIndex("ExcursionId", "AsientoId")
                        .IsUnique();

                    b.ToTable("AsignacionesAsientos");
                });

            modelBuilder.Entity("infinitoBack.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cambios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClavePrimaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEntidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("infinitoBack.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ci")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaVencimientoCi")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("infinitoBack.Models.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("infinitoBack.Models.Excursion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantDias")
                        .HasColumnType("int");

                    b.Property<int>("CantLugares")
                        .HasColumnType("int");

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaSalida")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlantillaVehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("PlantillaVehiculoId");

                    b.ToTable("Excursiones");
                });

            modelBuilder.Entity("infinitoBack.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("infinitoBack.Models.Paquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDestino")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Seña")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdDestino");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("infinitoBack.Models.PlantillaVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombrePlantilla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalColumnas")
                        .HasColumnType("int");

                    b.Property<int>("TotalFilas")
                        .HasColumnType("int");

                    b.Property<int>("TotalPisos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlantillasVehiculos");
                });

            modelBuilder.Entity("infinitoBack.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoReserva")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdClientePagador")
                        .HasColumnType("int");

                    b.Property<int>("IdExcursion")
                        .HasColumnType("int");

                    b.Property<int>("IdPaquete")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdClientePagador");

                    b.HasIndex("IdExcursion");

                    b.HasIndex("IdPaquete");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("infinitoBack.Models.ReservaCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsignacionAsientoId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ReservaId", "ClienteId");

                    b.ToTable("ReservaCliente");
                });

            modelBuilder.Entity("infinitoBack.Models.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<int>("FormaDePago")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdReserva");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("infinitoBack.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("infinitoBack.Models.Asiento", b =>
                {
                    b.HasOne("infinitoBack.Models.PlantillaVehiculo", "PlantillaVehiculo")
                        .WithMany("Asientos")
                        .HasForeignKey("PlantillaVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantillaVehiculo");
                });

            modelBuilder.Entity("infinitoBack.Models.AsignacionAsiento", b =>
                {
                    b.HasOne("infinitoBack.Models.Asiento", "Asiento")
                        .WithMany()
                        .HasForeignKey("AsientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("infinitoBack.Models.Excursion", "Excursion")
                        .WithMany("Asignaciones")
                        .HasForeignKey("ExcursionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("infinitoBack.Models.ReservaCliente", "ReservaCliente")
                        .WithOne("AsignacionAsiento")
                        .HasForeignKey("infinitoBack.Models.AsignacionAsiento", "ReservaClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("Excursion");

                    b.Navigation("ReservaCliente");
                });

            modelBuilder.Entity("infinitoBack.Models.Destino", b =>
                {
                    b.HasOne("infinitoBack.Models.Pais", "Pais")
                        .WithMany("Destinos")
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("infinitoBack.Models.Excursion", b =>
                {
                    b.HasOne("infinitoBack.Models.Destino", "Destino")
                        .WithMany("Excursiones")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("infinitoBack.Models.PlantillaVehiculo", "PlantillaVehiculo")
                        .WithMany("Excursiones")
                        .HasForeignKey("PlantillaVehiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Destino");

                    b.Navigation("PlantillaVehiculo");
                });

            modelBuilder.Entity("infinitoBack.Models.Paquete", b =>
                {
                    b.HasOne("infinitoBack.Models.Destino", "Destino")
                        .WithMany("Paquetes")
                        .HasForeignKey("IdDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("infinitoBack.Models.Reserva", b =>
                {
                    b.HasOne("infinitoBack.Models.Cliente", "ClientePagador")
                        .WithMany("ReservasPagas")
                        .HasForeignKey("IdClientePagador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("infinitoBack.Models.Excursion", "Excursion")
                        .WithMany("Reservas")
                        .HasForeignKey("IdExcursion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("infinitoBack.Models.Paquete", "Paquete")
                        .WithMany()
                        .HasForeignKey("IdPaquete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientePagador");

                    b.Navigation("Excursion");

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("infinitoBack.Models.ReservaCliente", b =>
                {
                    b.HasOne("infinitoBack.Models.Cliente", "Cliente")
                        .WithMany("ReservaClientes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("infinitoBack.Models.Reserva", "Reserva")
                        .WithMany("ReservaClientes")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("infinitoBack.Models.Transaccion", b =>
                {
                    b.HasOne("infinitoBack.Models.Cliente", "Cliente")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("infinitoBack.Models.Reserva", "Reserva")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("infinitoBack.Models.Cliente", b =>
                {
                    b.Navigation("ReservaClientes");

                    b.Navigation("ReservasPagas");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("infinitoBack.Models.Destino", b =>
                {
                    b.Navigation("Excursiones");

                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("infinitoBack.Models.Excursion", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("infinitoBack.Models.Pais", b =>
                {
                    b.Navigation("Destinos");
                });

            modelBuilder.Entity("infinitoBack.Models.PlantillaVehiculo", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("Excursiones");
                });

            modelBuilder.Entity("infinitoBack.Models.Reserva", b =>
                {
                    b.Navigation("ReservaClientes");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("infinitoBack.Models.ReservaCliente", b =>
                {
                    b.Navigation("AsignacionAsiento");
                });
#pragma warning restore 612, 618
        }
    }
}
